image:https://travis-ci.org/vmj/http-server.svg?branch=master["Build Status", link="https://travis-ci.org/vmj/http-server"]

= A simple JDK HTTP server

Build requirements:

 * JDK 8 (not tested with 9)

Runtime requirements:

 * JRE 8 (not tested with 9)

== Build

You do not need Gradle installed.  Instead, use the provided wrapper:

 ./gradlew assemble

On first invocation, it will download Gradle.
Then it will build the executable JAR of the application.

== Run

 java -jar build/libs/http-server-1.0-SNAPSHOT.jar

The server will start listening on localhost port 9000.

Stop the server with interrupt signal, typically CTRL-C.

== Test

While the server is running, hit it with re requests.  E.g.:

 curl --head http://localhost:9000/
 curl -v -X OPTIONS http://localhost:9000/
 curl -v http://localhost:9000/

== Docker

If you've got Docker, you can build this app into a docker image:

 ./gradlew dockerImage

And then run the container:

 docker run --rm -it -p9000:9000 vmj0/http-server:java8

Now the same test commands should work.
(Use `docker ps` and `docker stop CONTAINER_ID` to cleanup).
